[workspace]
members = ["src/libkrun", "src/krun_input", "src/krun", "examples/rust_vm"]
exclude = ["examples/gtk_display"]
resolver = "2"

[profile.dev]
#panic = "abort"

[profile.release]
#panic = "abort"
lto = true
